#!/usr/bin/env bash
#Run an infinite loop and trap all signal from SIGTERM
echo $$ > /var/run/myscript.pid
trap 'echo I hate the kill command ; rm -f /var/run/myscript.pid ; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'rm -f /var/run/myscript.pid' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
